Improve typing for MathJsChain (#2537)
* Make MathJsChain generic

* Start converting chain methods to overload `this`

* Properly type chain().bignumber()

* Split boolean type definition into separate overloads

* Add proper boolean chain definition

* Add proper complex chain definition

* Add proper createUnit chain definition

* Add proper createUnit chain definition

* Add proper index chain definition

* Add proper matrix chain definition

* Add proper number type definition

* Add proper sparse chain definition

* Add proper splitUnit chain definition

* Split string type definition into multiple overloads

* Add proper string chain definition

* Correct unit typings by splitting into multiple overloads

* Add proper unit chain definition

* Add proper compile chain definition

* Split evaluate type definition into multiple overloads

* Add proper evaluate chain definition

* Add proper parse chain definition

* Add proper parser chain definition

* Add proper resolve chain definition

* Add proper derivative chain definition

* Split lsolve type definition into multiple overloads

* Add proper lsolve chain definition

* Extract LUDecomposition type

* Add proper lup chain definition

* Remove incorrect number arg type and split lusolve into multiple overloads

* Remove unnecessary done checks

* Add proper lusolve chain definition

* Extract QRDecomposition type

* Add proper qr chain definition

* Add proper rationalize chain definition

* Add proper simplify chain definition

* Extract SLUDecomposition type

* Add proper slu chain definition

* Split usolve into multiple overloads

* Add proper usolve chain definition

* Add proper abs chain definition

* Add proper add chain definition

* Add proper apply chain definition

* Add proper cbrt chain definition

* Add proper ceil chain definition

* Add fix, floor, and round chain defs

* Add proper cube chain definition

* Add proper divide chain definition

* Add proper dot* chain definitions

* Add proper exp, expm1 chain definitions

* Add proper gcd chain definition

* Add proper hypot chain definition

* Add proper lcm chain definition

* Copy over remaining definitions and comment out

* Convert rest of chain fns

* Format

* Various fixes

* Fix lint

* Remove incorrect mathjs complex chain type

* Extract FractionDefinition type so that typescript doesn't confuse `object` with `MathCollection`

* Fix createUnit error

* Fix parser

* Remove parser from MathJsChain as it doesn't actually work...

Error "Uncaught TypeError: Too many arguments in function parser (expected: 0, actual: 1)" is thrown

* Fix apply test

* Remove fraction as acceptable value for cbrt

Doesn't actually work, throws "Cannot implicitly convert a Fraction to BigNumber or vice versa. Use function bignumber(x) to convert to BigNumber or fraction(x) to convert to Fraction."

* Fix unit

* Remove `Unit` as acceptable type for cbrt

Throws error: " Unexpected type of argument in function isNegative (expected: number or BigNumber or Fraction or Unit or Array or Matrix or string or boolean, actual: null, index: 0)"

* Fix more units

* Fix gcd chain types

* Format

* Improve lusolve type tests

* Make `add` chain type behave same as normal `add` type

* Improve `re` and `im` types and chain types

* Format

* Whoops

* Linty lint lint

* Fix lusolve tests

* Format